# Generated by Django 5.1.7 on 2025-04-08 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_remove_patient_phone_number_alter_provider_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='patient',
            name='first',
            field=models.CharField(default='John', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='last',
            field=models.CharField(default='Doe', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
