# Generated by Django 4.2.20 on 2025-04-26 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_remove_patient_address_remove_patient_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='medications_times',
        ),
        migrations.AlterField(
            model_name='patient',
            name='first',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med', models.CharField(max_length=50)),
                ('day', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], default='MONDAY', max_length=9)),
                ('hour', models.IntegerField(choices=[('one', 1), ('two', 2), ('three', 3), ('four', 4), ('five', 5), ('six', 6), ('seven', 7), ('eight', 8), ('nine', 9), ('ten', 10), ('eleven', 11), ('twelve', 12)], default='one')),
                ('min', models.IntegerField(choices=[('zero', 0), ('fifteen', 15), ('thirty', 30), ('fortyfive', 45)], default='zero')),
                ('meridiem', models.CharField(choices=[('AM', 'am'), ('PM', 'pm')], default='AM', max_length=2)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='providers.patient')),
            ],
        ),
    ]
