# Generated by Django 5.1.7 on 2025-04-27 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_remove_patient_medications_times_alter_patient_first_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='day',
            field=models.CharField(choices=[('MONDAY', 'MONDAY'), ('TUESDAY', 'TUESDAY'), ('WEDNESDAY', 'WEDNESDAY'), ('THURSDAY', 'THURSDAY'), ('FRIDAY', 'FRIDAY'), ('SATURDAY', 'SATURDAY'), ('SUNDAY', 'SUNDAY')], max_length=9),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='hour',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)]),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='meridiem',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='min',
            field=models.IntegerField(choices=[(0, 0), (15, 15), (30, 30), (45, 45)]),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_time', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='providers.patient')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reports', to='providers.prescription')),
            ],
        ),
    ]
