# Generated by Django 4.2.20 on 2025-04-27 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_alter_prescription_day_alter_prescription_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='providers.patient'),
        ),
        migrations.AlterField(
            model_name='report',
            name='prescription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reports', to='providers.prescription'),
        ),
    ]
