name: Email Reminder

#run every 15 minutes
on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  send-reminders:
    runs-on: ubuntu-latest

    #github action
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.6"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Emailer Command
        env:
          EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
        run: |
          python RemediBackend/manage.py emailer
